### ISSUE TITLE
Adding screenshots

### ISSUE THREAD

**Issue by locness3** [Aris-t2/NoiaButtons#2]

**Comment by locness3** [comment]
Why closed @Aris-t2 ?

**Comment by Aris-t2** [comment]
Because your post is empty and what exactly has "adding screenshots"  to do with NoiaButtons?

**Comment by locness3** [comment]
I mean adding screenshots to the readme or something, so we can see how it looks like. i guess the explanation isn't necessary.

**Comment by Aris-t2** [comment]
That is where you were wrong. ;-)

A proper request would look like:

> Is it possible to add some screenshots or preview images to see what kind of features this project offers?

**Comment by Aris-t2** [comment]
I would have answered:

> There is such an image (noiabuttons.png) within this projects files: https://github.com/Aris-t2/NoiaButtons/blob/master/noiabuttons.png
> It even is on the main page.
